export const FRIEND_GET_SUCCESS = "FRIEND_GET_SUCCESS";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SOCKET_MESSAGE_SUCCESS = "SOCKET_MESSAGE_SUCCESS";
